apiVersion: V1
network:
  Listen: any
  httpPort: 8080
  httpsPort: 8443
policy:
  query: grant_new_nonce = data.kbridge.grant_new_nonce; data.kbridge.get_principals[get_principals]
  policy: ""
  nonceLifetime: 60
  keytabSoftLifetime: 120
  keytabHardLifetime: 600
logging:
  logLevel: info
  logFormat: json
  outputPaths:
  - stderr
  errorOutputPaths:
  - stderr
data:
  principals:
  - superman@EXAMPLE.COM
  - birdman@EXAMPLE.COM
