apiVersion: V1
network:
  Listen: any
  httpPort: 8080
  httpsPort: 8443
  tlscert: |-
    -----BEGIN CERTIFICATE-----
    MIICMDCCAbUCCQDfhpjqkd8ewjAKBggqhkjOPQQDAjCBgDELMAkGA1UEBhMCVVMx
    CzAJBgNVBAgMAlRYMRIwEAYDVQQHDAlTb3V0aGxha2UxDTALBgNVBAoMBEpvZHkx
    DTALBgNVBAsMBEpvZHkxEDAOBgNVBAMMB2V4YW1wbGUxIDAeBgkqhkiG9w0BCQEW
    EWFkbWluQGV4YW1wbGUuY29tMB4XDTIwMTAwNjIxMjUwOVoXDTMwMTAwNDIxMjUw
    OVowgYAxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJUWDESMBAGA1UEBwwJU291dGhs
    YWtlMQ0wCwYDVQQKDARKb2R5MQ0wCwYDVQQLDARKb2R5MRAwDgYDVQQDDAdleGFt
    cGxlMSAwHgYJKoZIhvcNAQkBFhFhZG1pbkBleGFtcGxlLmNvbTB2MBAGByqGSM49
    AgEGBSuBBAAiA2IABH5IWn5ZRoCBxiaoWcHxsR8ozPN5zsnoBRT/aI+b5kQYxnOr
    /Qd3tFnuq955BpfAbuGMfieqrrMop1wkcysz3KcglqlzUTy/Kk+FmmNWWUA/KE1W
    Z70r0u9nG1FSQgHLtTAKBggqhkjOPQQDAgNpADBmAjEAueGyOviFCHJDqJxv+sZA
    oSXPQqUnGzTfiOBT+e/iSXPuedrq2aTl9iDxjX3I/kLQAjEAnzZM29NgpI1D/28G
    HyMaJavNYa31o1fSMKGW67zNV0LNy3X3FSyPLbVX4KT3Jy13
    -----END CERTIFICATE-----
  tlsKey: |-
    -----BEGIN EC PRIVATE KEY-----
    MIGkAgEBBDBWh9l1d6MvJeEU9wfo4GcLULM8NU01h5fej7h8NMBjLdjWEwt4Ted8
    AxAnwk018C6gBwYFK4EEACKhZANiAAR+SFp+WUaAgcYmqFnB8bEfKMzzec7J6AUU
    /2iPm+ZEGMZzq/0Hd7RZ7qveeQaXwG7hjH4nqq6zKKdcJHMrM9ynIJapc1E8vypP
    hZpjVllAPyhNVme9K9LvZxtRUkIBy7U=
    -----END EC PRIVATE KEY-----
policy:
  query: auth = data.kbridge.auth; data.kbridge.principals[principals]
  policy: "\npackage kbridge\n\t\ndefault auth = false\n\nauth {\n\tinput.iss == \"https://api.console.aporeto.com/v/1/namespaces/5ddc396b9facec0001d3c886/oauthinfo\"\n}\n\nprincipals[grant] {\n\tgrant := split(input.service.keytab,\",\")\n}\n\n"
  nonceLifetime: 60
  keytabTimePeriod: FiveMinute
  seed: this is not a good seed
logging:
  logLevel: debug
  logFormat: json
  outputPaths:
  - stderr
  errorOutputPaths:
  - stderr
data:
  principals:
  - superman@EXAMPLE.COM
  - birdman@EXAMPLE.COM
