apiVersion: V1
network:
  Listen: any
  httpPort: 8080
  httpsPort: 8443
policy:
  query: grant_new_nonce = data.kbridge.grant_new_nonce; data.kbridge.get_principals[get_principals]
  policy: "\npackage kbridge\n\ndefault grant_new_nonce = false\ngrant_new_nonce {\n\tinput.iss == \"https://api.console.aporeto.com/v/1/namespaces/5ddc396b9facec0001d3c886/oauthinfo\"\n}\nget_principals[grant] {\n\tgrant := split(input.claims.service.keytab,\",\")\n}\n"
  nonceLifetime: 60
  keytabLifetime: 120
logging:
  logLevel: info
  logFormat: json
  outputPaths:
  - stderr
  errorOutputPaths:
  - stderr
data:
  principals:
  - superman@EXAMPLE.COM
  - birdman@EXAMPLE.COM
