nonce:
  lifetime: 60
policy:
  query: grant_new_nonce = data.kbridge.grant_new_nonce; data.kbridge.get_principals[get_principals]
  policy: "\npackage kbridge\n\t\ndefault grant_new_nonce = false\n\ngrant_new_nonce {\n\tinput.iss == \"https://api.console.aporeto.com/v/1/namespaces/5ddc396b9facec0001d3c886/oauthinfo\"\n}\n\nget_principals[grant] {\n\tgrant := split(input.claims.service.keytab,\",\")\n}\n"
token: {}
keytab:
  lifetime: 300
  principals:
  - superman@EXAMPLE.COM
  - birdman@EXAMPLE.COM
httpPort: 8080
httpsPort: 8443
