#!/bin/bash

function main() {
  cd "$(dirname "$0")" || return 2
  source libcommon || return 2
  source settings || return 2
  sanity_check || return 2
  local audience
  audience="default"
  [[ $1 ]] && audience="$1"
  local r
  r=$(ssh -q -t ${RUSER}@${RHOST} "./oneshot $audience")
  [[ $r ]] || {
    err "Failed to get token"
    return 3
  }
  echo "$r"
  return 0
}

main "$@"
