#!/bin/bash

PRINCIPAL="superman@EXAMPLE.COM"
KBRIDGE=""
METADATA="169.254.254.1"

function main() {

  local token
  local nonce

  err "Getting token"
  token=$(curl -s -H 'X-Aporeto-Metadata: secrets' "http://${METADATA}/token?type=OAUTH&audience=initial") || {
    err "Failed to get token"
  }

  err "Getting nonce"
  nonce=$(curl --fail -s "${KBRIDGE}"/getnonce\?bearertoken="$token") || {
    err "Failed to get nonce"
  }

  err "Getting token again with aud set to nonce"
  token=$(curl -s -H 'X-Aporeto-Metadata: secrets' "http://${METADATA}/token?type=OAUTH&audience=$nonce") || {
    err "Failed to get token"
  }

  err "Getting keytab with token"
  keytab=$(curl --fail -s "${KBRIDGE}"/getkeytab\?bearertoken="$token"\&principal="$PRINCIPAL") || {
    err "Failed to get keytab"
  }

  trap cleanup EXIT
  tmp=$(mktemp)
  echo "$keytab" | base64 -d > "$tmp"

  cp "$tmp" auto.keytab
  # err "Getting Kerberos ticket"
  # kinit -k "$tmp"
  # return 0
}

function cleanup() { [[ "$tmp" ]] && rm -rf "$tmp"; }

function err() { echo "$@" 1>&2; }

main "$@"
