#!/bin/bash

RHOST="ec2-18-219-114-244.us-east-2.compute.amazonaws.com"
RUSER="admin"

function main() {
  cd "$(dirname "$0")" || return 2
  local aud
  aud=$1
  [[ $aud ]] || { err "Usage: $0 audience"; return 2; }
  rm -rf token || return 2
  local tmp
  tmp=$(mktemp)
  # export TOKEN=
  ssh -q -t ${RUSER}@${RHOST} "./oneshot $aud" > "$tmp" || {
    err "Failed to get token"
    rm -rf "$tmp"
    return 3
  }
  printf "export TOKEN=" > token
  cat "$tmp" >> token
  rm -rf "$tmp"
  return 0
}

function err() { echo "$@" 1>&2; }

main "$@"
